---
- name: Fetch current configuration from Fortigate firewall
  hosts: 10.241.14.12
  connection: paramiko
  gather_facts: no

  tasks:
    - name: get all
      fortinet.fortios.fortios_configuration_fact:
         vdom: root
         access_token: ""
         selector: log_custom-field

    - name: Display current configuration
      debug:
        msg: "{{ current_config }}"
