---
- name: Execute backup command on FortiGate device
  hosts: 10.241.14.12
  gather_facts: no
  tasks:
    - name: Set timestamp variable
      set_fact:
        backup_timestamp: "{{ lookup('pipe', 'date +%Y%m%d%H%M%S') }}"
        #backup_username: jc
        #backup_password: Vc9dq2WFiX8kG0OnTuhF
    
    - name: Run the backup command
      raw: "execute backup config sftp fortibackup_{{ backup_timestamp }}.txt 10.241.14.10:22 {{ ansible_user }} {{ ansible_ssh_pass }}"
      register: backup_command_output

    - name: Display the output of the backup command
      debug:
        var: backup_command_output.stdout
