---
- name: Fetch current configuration from Fortigate firewall
  hosts: 10.241.14.12
  gather_facts: no

  tasks:
    - name: Run show command
      ansible.builtin.shell:
        cmd: "show"
      register: show_output

    - name: Display show command output
      debug:
        msg: "{{ show_output.stdout }}"
