---
- name: Fetch current configuration from Fortigate firewall
  hosts: 10.241.14.12
  gather_facts: no

  tasks:
    - name: get single
      fortinet.fortios.fortios_configuration_fact:
      vdom: root
      access_token: ""
      selector: log_custom-field
      params:
          id: "3"

    - name: Display current configuration
      debug:
        msg: "{{ current_config }}"
