---
- name: Backup FortiGate configuration and transfer to SFTP server
  hosts: 10.241.14.12
  gather_facts: no

  tasks:
    - name: Backup FortiGate configuration to local file
      fortios_config:
        action: backup
        backup_path: /tmp/fortigate_config_backup.conf

    - name: Transfer configuration backup to SFTP server
      delegate_to: localhost
      sftp:
        src: /tmp/fortigate_config_backup.conf
        dest: /home/jc/fortigate_config_backup.conf
        host: 10.241.14.10
        port: 22
        user: jc
        password: Vc9dq2WFiX8kG0OnTuhF
