---
- name: Execute command on remote host
  hosts: 10.241.14.12
  gather_facts: no
  tasks:
    - name: Run the 'show' command
      raw: show
      register: show_command_output

    - name: Display the output of the 'show' command
      debug:
        var: show_command_output.stdout
