---
- name: Backup current configuration from Fortigate firewall to SFTP server
  hosts: 10.241.14.12
  gather_facts: no

  tasks:
    - name: Run backup command
        cmd: "execute backup config sftp fortibackup.txt 10.241.14.10:22 jc Vc9dq2WFiX8kG0OnTuhF"
