---
- name: Execute backup command on FortiGate device
  hosts: all
  gather_facts: no
  vars:
    backup_server: "10.241.14.10:22"
    backup_filename: "fortibackup_{{ lookup('pipe', 'date +%Y%m%d%H%M%S') }}.txt"
  tasks:
    - name: Set backup command
      set_fact:
        backup_command: "execute backup config sftp {{ backup_filename }} {{ backup_server }} {{ ansible_user }} {{ ansible_ssh_pass }}"
    
    - name: Display the backup command
      debug:
        msg: "Executing command: {{ backup_command }}"

    - name: Run the backup command
      raw: "{{ backup_command }}"
      register: backup_command_output
